language: node_js
matrix:
  include:
    - node_js: node
    - node_js: 4
    - node_js: 0.12
    - node_js: node
      env: NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
  allow_failures:
    - env: NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  webhooks: http://webhook.hakatashi.com/travis
